'use strict';
const $=id=>document.getElementById(id);
const make=(tag,content,cls)=>{const x=document.createElement(tag);if(content!==undefined)x.textContent=content;if(cls)x.className=cls;return x;};
let csrf='',settings=null,running=false;
const errors={INVALID_LOGIN:'Username or password was not accepted.',ADMIN_PASSWORD_NOT_CONFIGURED:'Admin password is not configured on the server.',LOGIN_RATE_LIMITED:'Too many login attempts. Try again after the five-minute rate window.',PASSWORD_LENGTH_INVALID:'Use 12–128 characters.',NEW_PASSWORD_MUST_DIFFER:'Choose a different password.',CAPTURE_PAUSED:'Research is paused. Resume it before starting a pilot step.',SETTINGS_CHANGED_RELOAD:'Another request changed these controls. Refresh before trying again.',DAILY_PILOT_LIMIT_REACHED:'The three-run UTC daily budget has been reached. Existing runs can still be resumed.',ADMIN_STORAGE_OR_OPERATION_UNAVAILABLE:'Admin storage or operation unavailable. Verify migration 0022 and inspect server logs.',LOGIN_REQUIRED:'Your session expired. Sign in again.'};
function message(value,error=false){$('message').textContent=value;$('message').className='message '+(error?'error':'success');$('message').hidden=false;}
function show(id){for(const x of ['loading','login','change','console'])$(x).hidden=x!==id;}
async function api(path,method='GET',data,extra={}){const headers={...extra};if(method!=='GET'){headers['Content-Type']='application/json';if(csrf)headers['X-CSRF-Token']=csrf;}const response=await fetch('/api/operator'+path,{method,headers,credentials:'same-origin',cache:'no-store',body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok){if(response.status===401&&result.error_code==='LOGIN_REQUIRED'){csrf='';show('login');}throw Error(errors[result.error_code]||result.error_code||'Request failed.');}return result;}
async function session(){try{const s=await api('/session');csrf=s.csrf_token||'';if(!s.authenticated)show('login');else{show('console');await refresh();}}catch(e){show('loading');$('loading').replaceChildren(make('h2','Admin is not ready'),make('p',e.message));}}
function bindForm(id,handler){$(id).addEventListener('submit',async e=>{e.preventDefault();const buttons=[...e.target.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await handler();}catch(error){message(error.message,true);}finally{buttons.forEach(b=>b.disabled=false);}});}
bindForm('login-form',async()=>{const pass=$('password').value;$('password').value='';const s=await api('/login','POST',{username:$('username').value,password:pass});csrf=s.csrf_token;show('console');await refresh();});
bindForm('change-form',async()=>{const current=$('current-password').value,next=$('new-password').value;$('current-password').value='';$('new-password').value='';const s=await api('/password','POST',{current_password:current,new_password:next});csrf=s.csrf_token;show('console');message('Password changed. Previous sessions were revoked.');await refresh();});
async function logout(){try{await api('/logout','POST',{});csrf='';show('login');}catch(e){message(e.message,true);}}
$('logout').addEventListener('click',logout);$('change-logout').addEventListener('click',logout);$('password-button').addEventListener('click',()=>show('change'));
function renderRuns(runs){$('runs').replaceChildren();if(!runs.length){$('runs').append(make('div','No manual pilot runs yet. Starting a run creates a durable, resumable record.','empty'));return;}for(const r of runs){const card=make('article',undefined,'card run'),head=make('div',undefined,'run-head'),title=make('div');title.append(make('strong',r.created_at),make('div',r.run_id,'mono hint'));head.append(title);if(r.items.some(i=>['PENDING','RUNNING'].includes(i.status))){const resume=make('button','Resume','secondary');resume.disabled=running||!settings.capture_enabled;resume.addEventListener('click',()=>drive(r.run_id));head.append(resume);}card.append(head);const wrap=make('div',undefined,'table-wrap'),table=make('table'),thead=make('thead'),tr=make('tr');for(const label of ['Stock','Task','Research outcome','Price date','Evidence / issue'])tr.append(make('th',label));thead.append(tr);table.append(thead);const tb=make('tbody');for(const item of r.items){const row=make('tr'),v=item.result||{},state=make('td');state.append(make('span',item.status,'status '+item.status));row.append(make('td',item.ticker),state,make('td',v.decision_status? v.decision_status+' / '+v.action:'Not yet captured'),make('td',v.price_date||'—'));const info=make('td');if(v.decision_id){const link=make('a','Open stock journal');link.href='/agents/'+encodeURIComponent(item.ticker);info.append(link,make('div',v.decision_id,'mono hint'));}if(v.error_code)info.append(make('p',v.error_code));if(v.provider_status)info.append(make('div','Massive: '+v.provider_status+' · News: '+v.news_status,'hint'));if(v.blockers&&v.blockers.length)info.append(make('p',v.blockers.join(' · '),'hint'));row.append(info);tb.append(row);}table.append(tb);wrap.append(table);card.append(wrap);$('runs').append(card);}}
async function refresh(){try{const data=await api('/dashboard');settings=data.controls;$('capture-state').textContent=settings.capture_enabled?'Research running':'Research paused';$('capture-detail').textContent='Control version '+settings.version+' · No redeploy required.';$('toggle-capture').textContent=settings.capture_paused?'Resume research':'Pause research';$('run-pilot').disabled=running||!settings.capture_enabled;$('updated').textContent='Controls saved at '+settings.updated_at;renderRuns(data.runs);const massive=data.connections.massive;$('massive-state').textContent=massive.configured?'Server-side key configured':'No server-side key configured';$('observations').replaceChildren();for(const o of massive.observations){const div=make('div',undefined,'observation');div.append(make('strong',o.ticker),make('span',o.status+' · '+(o.market_date||'No market date')));$('observations').append(div);}$('audit').replaceChildren();for(const e of data.audit){const d=make('div',undefined,'audit-item');d.append(make('strong',e.event),make('p',e.actor+' · '+e.occurred_at,'hint'),make('p',JSON.stringify(e.details),'mono'));$('audit').append(d);}if(!data.audit.length)$('audit').append(make('p','No administrative events.','hint'));}catch(e){message(e.message,true);}}
$('refresh').addEventListener('click',refresh);
$('toggle-capture').addEventListener('click',async()=>{if(!settings)return;const paused=!settings.capture_paused;const reason=window.prompt((paused?'Pause':'Resume')+' research: enter a short reason for the audit log.');if(reason===null)return;try{await api('/controls','POST',{capture_paused:paused,expected_version:settings.version,reason});message(paused?'New research captures are paused. In-flight work may finish.':'Research resumed.');await refresh();}catch(e){message(e.message,true);}});
async function drive(runId){if(running)return;running=true;try{for(let i=0;i<5;i++){await refresh();const result=await api('/runs/'+encodeURIComponent(runId)+'/step','POST',{});await refresh();if(result.status==='NO_RUNNABLE_ITEM'){message('No new step can be claimed. Refresh status; an existing step may still hold its lease.');break;}if(result.status==='FAILED'){message('A pilot step failed. The saved record preserves the error; no result was invented.',true);break;}}}catch(e){message(e.message,true);}finally{running=false;await refresh();}}
$('run-pilot').addEventListener('click',async()=>{if(running||!window.confirm('Run bounded research for all five pilot stocks? No trades will be placed.'))return;const runId=crypto.randomUUID();try{await api('/runs','POST',{request_id:runId});await drive(runId);}catch(e){message(e.message,true);}});
session();
